BUFFER_SIZE = 65536
RSA_KEY_PAIR_BITS = 1024
ENABLE_LOG=False

KEY_PAIR_DIR_NAME = "key_pair"
STORAGE_DIR_NAME = "storage"

PRIVATE_KEY_FILE_NAME = "private_key.pem"
PUBLIC_KEY_FILE_NAME = "public_key.pem"

SIGNATURE_METADATA_KEY = "Signature"